---
- name: Let's update the apt cache.
  apt: update_cache=yes
  sudo: yes

- name: Now we need to update the Raspbian distribution.
  apt: upgrade=yes
  sudo: yes

- name: Uninstall the massive wolfram-alpha engine
  apt: pkg={{ item }} state=absent
  sudo: yes
  with_items:
    - wolfram-engine

- name: Autoremove any unused packages.
  shell: "apt-get autoremove --assume-yes --purge"
  sudo: yes

- name: Let's Autoclean the system.
  shell: "apt-get autoclean --assume-yes"
  sudo: yes